[Chore] Implement dual-displays on mobile app
nimblehq/showcase-flutter-build-web-desktop pull request #56
Opened 2023-08-03 08:30 UTC by doannimble

## What happened 👀

Merge code support dual-displays on the mobile app to the origin

## Insight 📝

- Implement a second display screen
- Sync and display cart on second display

## Proof Of Work 📹

N/A

2023-08-03 09:12 UTC, luongvo commented on README.md
> +### How to use on the web/desktop:
I think we could have a new main section with the same level with `Run` for this and the below content

```suggestion
## Demonstration

### Flutter for Web and desktop
```

2023-08-03 09:12 UTC, luongvo commented on README.md
> +## How to use on the app
```suggestion
### Dual-displays integration on mobile
```

2023-08-03 09:12 UTC, luongvo commented on README.md
> +https://drive.google.com/file/d/19EjUpbiAurwyoNWKE5BLTzOBQSEQECnJ/view
```suggestion
#### Package used for dual-display

[Presentation Displays](https://pub.dev/packages/presentation_displays)

#### Proof of Work

https://drive.google.com/file/d/19EjUpbiAurwyoNWKE5BLTzOBQSEQECnJ/view
```

2023-08-03 09:40 UTC, doannimble commented on lib/di/module/database_module.dart
> +/*
I open it again since we were facing with the init hive when starting the dual display

2023-08-04 04:23 UTC, luongvo commented on README.md
> +---
@doannimble you seem missed this review? 👋

2023-08-04 04:30 UTC, doannimble commented on README.md
> +---
@luongvo Ah yes, my bad. I've removed it 🙏

2023-08-04 04:41 UTC, luongvo requested changes

2023-08-04 04:41 UTC, luongvo commented on README.md
> +## Dual-displays integration on mobile
This should be in lower level

```suggestion
### Dual-displays integration on mobile
```

2023-08-04 04:41 UTC, luongvo commented on README.md
> +### Proof of Work
Then

```suggestion
#### Package used for dual-display

[Presentation Displays](https://pub.dev/packages/presentation_displays)

#### Proof of Work
```

2023-08-04 04:41 UTC, luongvo commented on README.md
> +    - Mobile: `$ flutter run`
since we had instructions below to guide how to run the app on the web and desktop, should we optimize this section like this?

```suggestion
#### Mobile: 

    `$ flutter run`
```

2023-08-04 04:41 UTC, luongvo commented on README.md
> +> encountered during local development.
please revert to the original change, as its format is broken now

<img width="1021" alt="image" src="https://github.com/nimblehq/showcase-flutter-build-web-desktop/assets/16315358/f0fef700-379d-4fec-9971-141fffe70a3e">

2023-08-04 04:41 UTC, luongvo commented on README.md
> +      <img alt="Screenshot" src="https://github.com/nimblehq/showcase_flutter_build_ios_android/assets/88996251/b971e1a3-606f-42ab-a8a8-62e9ea379486" width="400">
We will merge https://github.com/nimblehq/showcase_flutter_build_ios_android into upstream and delete it after that so please migrate these assets to https://github.com/nimblehq/showcase-flutter-build-web-desktop 🙏

2023-08-04 04:41 UTC, luongvo commented on README.md
> +in [Releases](https://github.com/nimblehq/showcase_flutter_build_ios_android/releases)
we need to update the repo. it's now here https://github.com/nimblehq/showcase-flutter-build-web-desktop/releases

2023-08-04 04:41 UTC, luongvo commented on README.md
> +      <img alt="Screenshot" src="https://github.com/nimblehq/showcase_flutter_build_ios_android/assets/88996251/c136d02e-a571-4841-975a-a035851e4ebb" width="400">
and all as below 👇

2023-08-04 04:42 UTC, luongvo commented
Hi @doannimble, we mostly need to migrate all necessary README content and assets to the upstream, the rest lgmt 🙏

2023-08-04 04:54 UTC, doannimble commented on README.md
> +    - Mobile: `$ flutter run`
I think we can keep this to make it consistent 🤔

2023-08-04 04:55 UTC, luongvo commented on README.md
> +    - Mobile: `$ flutter run`
@doannimble, hmm, but that looks repetitive with 2 below sections on how to run the app on the web or windows.

2023-08-04 06:54 UTC, doannimble commented on README.md
> +    - Mobile: `$ flutter run`
@luongvo yes, for the detail, we should make them repetitive. But this looks like the list of commands, hence, creating another region is odd imo 🙏

2023-08-04 06:55 UTC, luongvo commented on README.md
> +    - Mobile: `$ flutter run`
@doannimble If you say so, not a big deal.

2023-08-04 07:36 UTC, chornerman commented on README.md
> +4. Now we can update the cart, and it will reflect to the second screen accordingly
```suggestion
4. Now we can update the cart, and it will reflect on the second screen accordingly
```

2023-08-04 07:36 UTC, chornerman commented on README.md
> +5. Finally, we click `Pay Now` to notify on the second screen shows the instruction payment the text
```suggestion
5. Finally, we click `Pay Now` to notify the second screen to show the instruction payment text
```

2023-08-04 07:48 UTC, luongvo approved these changes
All good now

2023-08-04 07:48 UTC, luongvo commented
@doannimble @chornerman Let's try to merge this soon 🙏

2023-08-04 07:49 UTC, chornerman approved these changes
lgtm 🚀

2023-08-04 08:06 UTC, merged